import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from "@/app/_components/header/Header";
import Navbar from "@/app/_components/navbar/Navbar";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className} >
      <body className={'dark:bg-[#1C1C1E] flex flex-col gap-4 dark:text-[#cccccf] box-border overflow-x-hidden'} >
      <Header/>
      <Navbar/>
      {children}
      </body>
    </html>
  )
}
